### PR TITLE
Implement Pivotal Tracker Activity Hooks processing

### PR DESCRIPTION
**Pull request by tchap**
As specified in https://github.com/salsaflow/salsaflow/wiki/Module:-Pivotal-Tracker

@realyze

### CODE REVIEW

**Comment by tchap** [comment]
Tested this manually using the Heroku try environment. The PT activity processing works as expected. Haven't tested the `implemented` label yet...

**Comment by realyze** [comment]
Looks good to me!

**Comment by realyze** [comment]
Just please rebase onto develop and ideally squash the changes.

**Comment by tchap** [comment]
It is on develop. Not sure we need to squash, I split the thing properly I think, and anyway, merging a pull request is not a fast-forward merge...

**Comment by tchap** [comment]
@realyze Did the manual testing part, fixed all the issues, should be working now.

**Pull request merged**
